### PR TITLE
Few improvements and two useful examples added

### PR DESCRIPTION
**Pull request by robang74**
Please, note that on my fork I set the version tag 0.1.1 on this commit which is the current HEAD of this repo

-> https://github.com/CODeRUS/github-sfos-build/commit/2f983ee67a0c38c8bb0dfb10ddfbbd55f6c91952

I wish our tags will be syncronised. My current head is 0.1.2. I hope this helps, R-

### CODE REVIEW

**Comment by CODeRUS** [comment]
hello, please change `robang74/github-sfos-apps-build`to this repo in your examples

**Comment by robang74** [comment]
Hi @CODeRUS , if I will change those example will not point anymore to my fork repo. After having accepted my pull the you can change by yourself and those examples will point to your repo. Best regards, R-

**Comment by CODeRUS** [comment]
@robang74 there is no reason in this PR then if you're going to keep and maintain your fork still

**Comment by robang74** [comment]
@CODeRUS , the reason for accepting my PR is to improve YOUR repository and keep it aligned with mine. This is the main reason because Github allows people to fork others people project: independent collaborative contributes exchanges without the need you give me the write access to your repository. However, it is your repo and it is your choice. Please, accept the PR or close it.

**Comment by CODeRUS** [comment]
yes so please do not create PR that require extra work to replace your links with mine. in general creating master -> master PR is BAD practice. if you want to contribute to my repo, then please create branch with changes specific for my repo

**Comment by robang74** [comment]
> yes so please do not create PR that require extra work to replace your links with mine. in general creating master -> master PR is BAD practice. if you want to contribute to my repo, then please create branch with changes specific for my repo

@CODeRUS please note that replacing the links into the examples files is something that YOU raised as a request to me but. there is no any problem to integrate such example AS-IS. Therefore, giving you a eye-by-eye answer like yours above: please do not ask me to do extra work for you but accept the PR or close it, as suggested.

It is also a kind of lesson for the real-life: do not expect and do not even ask that others people underlay your {rules, ethics, values, PoVs, etc.} but keep the best from then and leave behind the rest. I came to you with a gift (my PoV), if you do not like it (your PoV) feel free to refuse it but do not bother me with YOUR problems whatever they are.

That's all, R-

**Comment by Olf0** [comment]
LOL: Most of that stuff is copypasta from other('s) sources / authors, without naming them; a pattern you have been showing many times.  So much for "ethics, values", or you define these terms very differently.

P.S.: Being immune to accept some well meant guidance (e.g., "in general creating a master -> master PR is BAD practice."), but instead becoming snappy is a somewhat toxic reaction you show regularly.

P.P.S.: Please note that nobody has dismissed your ideas and PRs at FSO rsp.  GitHub on personal grounds, but because of the way they are presented (often egocentric), implemented (usually convoluted, sometimes erroneous, sometimes exhibiting a lack of technical understanding) and committed (e.g., see above).  But unfortunately you seem to take these replies personally, hence react accordingly with personal attacks, which results in rejection.

**Comment by robang74** [comment]
@Olf0 , it is not copy & paste from others sources but from the example linked by @CODeRUS  into his README.md that point towards your project, [here](https://github.com/storeman-developers/harbour-storeman/pull/170/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721).

Your project is under MIT licence, [here](https://github.com/storeman-developers/harbour-storeman/blob/devel/LICENSE). Which clearly states: "The above copyright notice and this permission notice (including the next paragraph) shall be included in **all copies or substantial portions** of the Software."

Now, the most similar file to my examples is this [one](https://github.com/storeman-developers/harbour-storeman/blob/devel/.github/workflows/build-sfos4.2_latest.yml). We can notice 3 things about this files:

1. it has not a header about copyright and authorship therefore no one "takes away" anything.
2. that file is the most long and complex of the four .yml files in that folder and it is constituted by 3 parts:
   a) a quite standard header {name, env, on, jobs}
   b) a repetition for i in i486, arm64, arm7hl; echo print the same 5 lines
   c) a quite standard footer about upload results
3. the most creative - or better it would be said - the most customized part is the header.

Now, the header is exactly the part that I decided to change for the good sake of many. Everything else for size and original contribute would not even enter into a trial for copyright infringement because considered public domain - or better said - the state of the arts: what everyone averaged skilled in this sector can easily learn an repeat in the same manner with a minimum effort, in fact.

Ok, it is not about the copyright law that obviously you do not even know because otherwise you would put the (C) notice in brief on every file but you did not. It is about courtesy. Courtesy of what? The fork is clearly states that it is a fork of an original project that link those files and also my fork link those files. Therefore everyone can easily found the original works.

Containers? Done in the past. 
Actions shell script? Done in the past.
Action .yml workflow? Done in the past. 

For three years everything was done - as in the state of art - what it was missing? 

A step-by-step guide and few as-less-customized-as-possible examples that would fit the needs of the most or many and can be deployed in near zero time and effort. This is my contribution: the art of simplification, generalization and easy deployment.

The world will enjoy your boutade here and [here](https://forum.sailfishos.org/t/create-a-release-and-build-your-app-for-sfos-on-github-in-few-minutes/16200/1) until the Earth will go around the Sun. Kisses. :-*

**Pull request closed without merging**
